included:
  - WeatherInParis
excluded:
  - .build
analyzer_rules:
  - unused_declaration
  - unused_import
disabled_rules:
  - identifier_name
  - unused_optional_binding
  - multiple_closures_with_trailing_closure
  - trailing_whitespace
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - explicit_init
  - fatal_error_message
  - todo
  - force_unwrapping
  - implicitly_unwrapped_optional
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
operator_whitespace:
  severity: error
colon:
  severity: error
vertical_whitespace:
  severity: error
unused_closure_parameter:
  severity: error
force_try:
  severity: error
type_body_length:
  warning: 250
  error: 350
function_body_length:
  warning: 30
  error: 100
cyclomatic_complexity:
  warning: 10
  error: 20
nesting:
  statement_level:
    warning: 3
function_parameter_count:
  warning: 4
  error: 5
todo:
  severity: warning